*&---------------------------------------------------------------------*
*& Include          ZPPC_DMP_001_TOP
*&---------------------------------------------------------------------*

TYPE-POOLS: TRUXS.
TYPE-POOLS: SLIS, ICON, KKBLO.
TABLES : ZTA_PP_001_DMP, MARC.

CONSTANTS:
  yes        VALUE 'X',
  no         VALUE space,
  c_vrsio(3) VALUE '000'.

TYPES :
  BEGIN OF GTY_HIDE ,
    NAME TYPE SCREEN-NAME,
  END OF GTY_HIDE.

TYPES : BEGIN OF TY_RD2,
          WERKS TYPE WERKS_D,
          BLDAT TYPE SY-DATUM,
          ZPER  TYPE CHAR03,
          ZYEAR TYPE CHAR04,
          MPLAN TYPE CHAR10,
          ZQTY  TYPE CHAR3,
          ZAMT  TYPE CHAR3,
          MACT  TYPE CHAR10,
          HACT  TYPE CHAR10,
          MJSV  TYPE CHAR10,
          HJSV  TYPE CHAR10,
          DEV   TYPE CHAR5,
        END OF TY_RD2.


*  TYPES : BEGIN OF ty_rd2,
*
*          END OF ty_rd2.


DATA : IT_SCREEN_RD1 TYPE STANDARD TABLE OF GTY_HIDE WITH HEADER LINE.

DATA :
  IT_TMP  TYPE TABLE OF ZTA_PP_001_DMP,
  WA_TMP  TYPE ZTA_PP_001_DMP,
  IT_TAB  TYPE TABLE OF ZTA_PP_001_DMP,
  WA_TAB  TYPE ZTA_PP_001_DMP,
  IT_TAB2 TYPE TABLE OF TY_RD2,
  WA_TAB2 TYPE TY_RD2
  .

DATA :
      X_FLAG TYPE BOOLEAN.

DATA : MAIN_CONT TYPE REF TO  CL_GUI_CUSTOM_CONTAINER.
DATA : SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
DATA : ALV_PART1 TYPE REF TO CL_GUI_CONTAINER.
DATA : ALV_PART2 TYPE REF TO CL_GUI_CONTAINER.
DATA : ALV_GRID1 TYPE REF TO CL_GUI_ALV_GRID.
DATA : ALV_GRID2 TYPE REF TO CL_GUI_ALV_GRID.

DATA:
  i_layout     TYPE slis_layout_alv,
  i_events     TYPE slis_t_event,
  i_fieldcat   TYPE slis_t_fieldcat_alv,
  i_print      TYPE slis_print_alv,
  i_list_top   TYPE slis_t_listheader,
  i_list_end   TYPE slis_t_listheader,
  i_sort       TYPE slis_t_sortinfo_alv,
  i_color      TYPE lvc_t_scol WITH HEADER LINE,
  wa_fieldcat  LIKE LINE OF i_fieldcat,
  i_variant    LIKE disvariant,
  i_selfield   TYPE slis_selfield,
  fcode        TYPE TABLE OF sy-ucomm,
  ok_code      TYPE sy-ucomm,
  data_count   TYPE i,
  header_count TYPE i,
  spec         TYPE char16,
  v_total      TYPE sy-pagno.


DATA:
  gs_extract1 LIKE disextract,
  gs_extract2 LIKE disextract.

SELECTION-SCREEN BEGIN OF BLOCK DM1 WITH FRAME TITLE TEXT-001.
  PARAMETERS : P_RAD1 RADIOBUTTON GROUP RB01 DEFAULT 'X' USER-COMMAND TEST,
               P_RAD2 RADIOBUTTON GROUP RB01.
SELECTION-SCREEN END OF BLOCK DM1.

SELECTION-SCREEN BEGIN OF BLOCK DM2A WITH FRAME TITLE TEXT-002 .
  PARAMETERS : P_WERKSB TYPE MARC-WERKS  MODIF ID MID,
               P_PERIOB TYPE ZTA_PP_001_DMP-ZPERIOD MODIF ID MID,
               P_YEARSB TYPE ZTA_PP_001_DMP-ZYEAR MODIF ID MID,
               P_MATNRB TYPE MARC-MATNR MODIF ID MID.
  SELECTION-SCREEN BEGIN OF LINE .
    SELECTION-SCREEN COMMENT 1(12) TEXT-210 FOR FIELD P_QTY1 MODIF ID MID.
    SELECTION-SCREEN POSITION 33 .
    PARAMETERS P_QTY1 TYPE ZTA_PP_001_DMP-ZQTY1 MODIF ID MID.
    SELECTION-SCREEN POSITION 50 .
    PARAMETERS P_UOM1 TYPE ZTA_PP_001_DMP-ZQTY1_UOM MODIF ID MID.
  SELECTION-SCREEN END OF LINE .

  SELECTION-SCREEN BEGIN OF LINE .
    SELECTION-SCREEN COMMENT 1(12) TEXT-211 FOR FIELD P_QTY2 MODIF ID MID.
    SELECTION-SCREEN POSITION 33 .
    PARAMETERS P_QTY2 TYPE ZTA_PP_001_DMP-ZQTY2 MODIF ID MID.
    SELECTION-SCREEN POSITION 50 .
    PARAMETERS P_UOM2 TYPE ZTA_PP_001_DMP-ZQTY2_UOM MODIF ID MID.
  SELECTION-SCREEN END OF LINE .



  SELECT-OPTIONS : P_WERKS FOR MARC-WERKS MODIF ID MOD,
                   P_PERIO FOR SY-DATUM(2) MODIF ID MOD,
                   P_YEARS FOR SY-DATUM(4) MODIF ID MOD,
                   P_MATNR FOR MARC-MATNR MODIF ID MOD.
SELECTION-SCREEN END OF BLOCK DM2A.

INITIALIZATION.
*  P_UOM1 = 'BCM'.
*  P_UOM2 = 'BCM'.

AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN.
    IF P_RAD1 = 'X'.
      IF SCREEN-GROUP1 = 'MOD'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.
      PERFORM F_GET_RAD1.
      PERFORM AT_SEL_RAD1.


    ELSEIF P_RAD2 = 'X'.
      IF SCREEN-GROUP1 = 'MID'.
        SCREEN-ACTIVE = 0.
        MODIFY SCREEN.
      ENDIF.

    ENDIF.
  ENDLOOP.
